[package]
name = "maimap-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
salvo = { version = "0.77", features = ["oapi"] }
tokio = { version = "1", features = ["macros"] }
tracing = "0.1"
tracing-subscriber = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
mongodb = "3"
thiserror = "2"
dotenv = "0.15.0"