name: maimap-backend-docker-ci

on:
  #  push:

  workflow_dispatch:

jobs:
  CargoTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Set up cache
        uses: Swatinem/rust-cache@v2

      - name: Set up env
        run: |
          echo "TEST_DATABASE_URI=${{ secrets.TEST_DATABASE_URI }}" > .env

      - name: Run test
        run: cargo test --features test-all

  BuildDockerImage:
    runs-on: ubuntu-latest
    needs: CargoTest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKER_TAG }}/maimap-backend:latest
          build-args: |
            ENV_FILE_URL=https://raw.githubusercontent.com/120MF/maimap-env/main/.env
            GITHUB_TOKEN=${{ secrets.GH_TOKEN }}
            CACHEBUST=${{ github.run_id }}-${{ github.run_number }}